/*
CREATE VIEW MEMBER_INFO AS
  SELECT M.MEMBER_ID, M.PASSWORD, M.NAME, M.BIRTHYEAR, 
         M.BIRTHMONTH, M.BIRTHDAY, M.ADDRESS, M.PHONE, M.POINT
         FROM MEMBERS AS M INNER JOIN GRADE AS G
         ON M.`POINT` >= G.LOW_POINT AND M.`POINT` <= G.HIGH_POINT;
         
*/

/*
CREATE VIEW REPLY_LIST AS
SELECT B.NUM AS BOARD_NUM, R.NUM AS REPLY_NUM, R.CONTENTS, R.`DATE`, R.WRITER 
  FROM REPLY AS R INNER JOIN BOARD AS B
  ON R.BNUM = B.NUM;
*/

/*
CREATE VIEW BOARD_LIST AS 
SELECT B.NUM AS BOARD_NUM, B.TITLE, B.CONTENTS, B.WRITER, M.NAME, B.`DATE`, B.VIEWS 
FROM BOARD AS B INNER JOIN MEMBERS AS M 
ON B.WRITER = M.MEMBER_ID
ORDER BY B.`DATE` DESC;
*/

